services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web-auth  # Specify the correct Dockerfile for the web service
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8080/auth  # Using keycloak as the hostname within the same Docker network
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
      - KEYCLOAK_CLIENT_SECRET=myclientsecret
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin-password
    depends_on:
      - keycloak

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak  # Specify the correct Dockerfile for the Keycloak service
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin-password
      - KC_HTTP_PORT=8080
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/myrealm.json
      - KC_DB=mssql
      - KC_DB_URL=jdbc:sqlserver://rsosqlserver.database.windows.net:1433;databaseName=auth_db
      - KC_DB_USERNAME=musicn
      - KC_DB_PASSWORD=nekiPogacarneki123
      - KC_DB_SCHEMA=dbo
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - ./keycloak-realm-config:/opt/keycloak/data/import  # Optional, if you want to import a realm
    command: ["start-dev", "--import-realm"]

networks:
  backend:
    driver: bridge
