# Use the official Keycloak image as a base image
FROM quay.io/keycloak/keycloak:latest

# Set environment variables (optional, can also be in docker-compose.yml)
ENV KEYCLOAK_IMPORT=/opt/keycloak/data/import/myrealm.json

# Copy the custom realm JSON file into the container
COPY keycloak-realm-config/myrealm.json /opt/keycloak/data/import/myrealm.json

# Expose the Keycloak HTTP port
EXPOSE 8080

# Start Keycloak and import the realm during initialization
CMD ["start-dev", "--import-realm"]
