replicaCount: 1

image:
  repository: rsocontainerregistry.azurecr.io/web-auth
  tag: v4
  containerPort: 8000

env:
  KEYCLOAK_SERVER_URL: "http://keycloak:8080/keycloak/"
  KEYCLOAK_REALM: "myrealm"
  KEYCLOAK_CLIENT_ID: "myclient"
  KEYCLOAK_CLIENT_SECRET: "myclientsecret"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin-password"

health:
  initialDelaySeconds: 20
  periodSeconds: 120
  path: healthz

