apiVersion: v1
kind: Service
metadata:
  name: web-auth
spec:
  selector:
    app: web-auth
  ports:
  - protocol: TCP
    port: {{ .Values.image.containerPort }}
    targetPort: {{ .Values.image.containerPort }}
  type: ClusterIP
