apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: rsocontainerregistry.azurecr.io/keycloak:v1
        ports:
        - containerPort: 8080
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin-password"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KEYCLOAK_IMPORT
          value: "/opt/keycloak/data/import/myrealm.json"
        - name: KC_DB
          value: "mssql"
        - name: KC_DB_URL
          value: "jdbc:sqlserver://rsosqlserver.database.windows.net:1433;databaseName=auth_db"
        - name: KC_DB_USERNAME
          value: "musicn"
        - name: KC_DB_PASSWORD
          value: "nekiPogacarneki123"
        - name: KC_DB_SCHEMA
          value: "dbo"