apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
        ports:
        - containerPort: {{ .Values.keycloak.containerPort }}
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "{{ .Values.keycloak.env.KC_BOOTSTRAP_ADMIN_USERNAME }}"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "{{ .Values.keycloak.env.KC_BOOTSTRAP_ADMIN_PASSWORD }}"
        - name: KC_HTTP_PORT
          value: "{{ .Values.keycloak.env.KC_HTTP_PORT }}"
        - name: KEYCLOAK_IMPORT
          value: "{{ .Values.keycloak.env.KEYCLOAK_IMPORT }}"
        - name: KC_DB
          value: "{{ .Values.keycloak.env.KC_DB }}"
        - name: KC_DB_URL
          value: "{{ .Values.keycloak.env.KC_DB_URL }}"
        - name: KC_DB_USERNAME
          value: "{{ .Values.keycloak.env.KC_DB_USERNAME }}"
        - name: KC_DB_PASSWORD
          value: "{{ .Values.keycloak.env.KC_DB_PASSWORD }}"
        - name: KC_DB_SCHEMA
          value: "{{ .Values.keycloak.env.KC_DB_SCHEMA }}"
